### ISSUE TITLE
Filter sentences related to Wikipedia features

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/common-voice-wiki-scraper#10]
While they are technically valid sentences, there are a lot of sentences referring to Wikipedia categories or pages:

> See "graph embedding" for other related topics.

> See Eusebius, Hist.

> See "List of the Catholic bishops of the United States"

In my opinion these should be removed.

**Comment by MichaelKohler** [comment]
I'm not sure if there is any way to recognize these :/

**Comment by nukeador** [comment]
@dabinat if you have ideas on how to detect this, please let us know.

**Comment by dabinat** [comment]
This really bothered me at first but now my opinion has changed on it. I don’t think this is an important issue now.

**Comment by nukeador** [comment]
OK, please close if you consider we won't be revising this in the future.

**Comment by dabinat** [comment]
I will close this but if anyone else feels this is an issue, feel free to reopen it.
