### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/common-voice-wiki-scraper#12]
Some sentences seem to have words missing, such as:

> They also released a best of album, "".

> Only the plural form "" is used even when addressing one person.

> The subspecies "C. graminis santonico" is associated with "".

It's hard to know what's causing this without knowing what the original sentence was. Maybe this has something to do with URLs?

**Comment by MichaelKohler** [comment]
There are also issues with unclosed quotes, possibly due to the WikiExtractor cutting off sentences.

@nukeador I think we could dupe this against #32 as that one covers both cases?

**Comment by nukeador** [comment]
Yep
