### ISSUE TITLE
Dupe detection

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/common-voice-wiki-scraper#14]
The wiki sentence dump had over 30K duplicate sentences so there should be some kind of duplicate detection built into the scraper tool.

**Comment by jaumeortola** [comment]
Duplicates can be removed just after the whole extraction. 
It would be better to keep a record of all previous sentences during the process, so we don't miss the opportunity to extract 3 new sentences from each article (if possible).

**Comment by nukeador** [comment]
The process is pretty heavy right now and it's taking a lot of hours to complete, @MichaelKohler @Gregoor what would be your recommendation here?

We should probably identify the % of dupes we are getting and if it's low enough maybe doing a post-clean-up instead of making the main process heavier?

**Comment by MichaelKohler** [comment]
https://github.com/Common-Voice/common-voice-wiki-scraper/blob/5fac23bd99db6edf64818af5e1dca5d9b134a4ce/src/extractor.rs#L57

I think there are several issues with that:
* @fiji-flo shouldn't `sentences` be sorted first, as dedup only removes consecutive dupes as per https://doc.rust-lang.org/std/vec/struct.Vec.html#method.dedup? .. or we could use a HashMap.
* This only dedupes within one "text", the Wiki export has many texts
* I agree that this should happen while choosing, as we otherwise might lose some possible additional extractions.

If we fix the problems above, there will be a perf impact, I can't say how much though off the top of my head.

**Comment by Gregoor** [comment]
Yeah I agree that we should dedupe while picking sentences to maximize the amount of total extracted sentences. And a HashSet is also the cheapest option that comes to my mind.
If we parallelize the process we should be able to more than make up for the cost we have to pay for this. Last time I tried my hand at it, I unfortunately didn't succeed, but happy to restart those efforts.

**Comment by iLeonidze** [comment]
Having issue with duplicates in output file:
```
Любой пользователь может создать новый объект.
Каждый объект может иметь описания на каждом из этих языков.
Также существует блог Викимапии.
Находится в созвездии Кит.
Это самое ближнее к нам скопление галактик.
Находится в созвездии Кит.
Находится в созвездии Кит.
Находится в созвездии Кит.
Это один из наиболее тусклых объектов в списке Мессье.
Два года служил сельским учителем.
Одно из самых известных звёздных скоплений.
Одно из самых известных звёздных скоплений.
Член Союза писателей России.
На небосводе галактика близка к знаменитому густонаселенному скоплению галактик в Печи.
Видима в любительский телескоп.
Родился в поч.
Галактика входит в Скопление Печи.
Однако сейчас нет возможности доказать это.
Галактика входит в Скопление Печи.
Галактика входит в состав Скопления Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Галактика входит в Скопление Печи.
Она имеет две малых галактики-сателлита.
Она находится относительно близко к нам.
В аванзалы с площади ведут два лестничных спуска и пандус.
Мать Умы является шведской подданной.
Это самая плохая из юг.
Это очень необычный объект.
Из династии Мушатинов.
```

**Comment by MichaelKohler** [comment]
Fixed with https://github.com/Common-Voice/common-voice-wiki-scraper/pull/76
