### ISSUE TITLE
Blacklist vs whitelist words

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/common-voice-wiki-scraper#23]
This is no probably a big issue, but I observed some symbols while testing the Spanish export, like Ω

I suspect there are not a lot of them, but it makes me thing if our rules should have a whitelisting instead of a blacklisting filter, so we can just define everything that is valid. This might not work for non-Latin scripts and we might want to consider both?

**Comment by nukeador** [comment]
@MichaelKohler can this be useful? https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists

**Comment by MichaelKohler** [comment]
@nukeador I guess #33 is the decision for this and this can be closed?

**Comment by nukeador** [comment]
Yeah, we can probably open a whitelist filter later if required by any language.

**Comment by Mte90** [comment]
For italian I was suggesting to do a regex with only the alphabet letter allowed so is more easy to filter that cases.

**Comment by nukeador** [comment]
But have in mind some word can use Italian alphabet letters and still be impossible to pronounce correctly fro most people :-P

**Comment by jaumeortola** [comment]
I think a whitelist is a much better approach. A list of correct (and common) words can be provided (from a dictionary). But it is impossible to provide a list of all possible misspellings. 

Could you implement a whitelist, please?

Some options regarding case conversion will be necessary. For example: Capitalized or upper-case versions of lower-case words are allowed? Yes/no.
