### ISSUE TITLE
Define letters that can't be together

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/common-voice-wiki-scraper#24]
In order to avoid non-Spanish words, it would be useful to define letters that can't be together in Spanish, so some foreign names and surnames can be filtered out easily.

**Comment by dabinat** [comment]
I have a whole bunch of these for English here, some of which may be relevant to other languages:

https://github.com/dabinat/cvtools/blob/master/sentence_validator.py

See containsForeignTerm() function.

**Comment by MichaelKohler** [comment]
Is this superseded by #33?

**Comment by nukeador** [comment]
Yes and no. This is something that can probably be solved by a regex, instead of a full blacklist.

**Comment by MichaelKohler** [comment]
See https://github.com/Common-Voice/common-voice-wiki-scraper/pull/54/files#diff-cfcc24568eca763d366295fdd6750c05R41 where this has basically been done. I'm not sure if we need a separate config for this.
