### ISSUE TITLE
Skip wikipedia categories

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/common-voice-wiki-scraper#25]
It might be interesting to have the ability to avoid articles in certain wikipedia categories. I can imagine that articles with some offensive language are tagged somehow.

**Comment by MichaelKohler** [comment]
This is already possible through the WikiExtractor script with the `--filter_category` flag. See https://github.com/attardi/wikiextractor. I don't think we should handle this on our side given that it already exists in the other script.

**Comment by MichaelKohler** [comment]
@nukeador can this be closed?
