### ISSUE TITLE
Abbreviation patterns not working?

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/common-voice-wiki-scraper#26]
Using 

```
abbreviation_patterns = ["[A-Z]+\\.*[A-Z]", "[A-Z]\\.$"]
```

I'm still getting sentences like this:

> E-Pass Technologies vs.

**Comment by MichaelKohler** [comment]
What exactly would you like the Regex to filter for? Neither of those regex definition matches that sentence. https://regex101.com/ might help :)

**Comment by MichaelKohler** [comment]
@nukeador can this be closed?
