### ISSUE TITLE
Unclosed " or double empty ""

### ISSUE THREAD

**Issue by Mte90** [Common-Voice/common-voice-wiki-scraper#32]
I am testing the italian rules and I see a lot of sentences like:
```
L'anno seguente fu acquistata dalla "Commodore International Ltd.
Esso non è un bene per nessuno"".
Nemini nimium bene est significa letteralmente: ""perché aspiriamo al superfluo?
```

Those are broken sentences because are unclosed or there are empty "", I don't think that is a regex problem in the rules file but something that the scraper consider as good sentences but they aren't and probably also other languages can have the same problem.

**Comment by MichaelKohler** [comment]
The thing is that these are already wrong coming from the WikiExtractor. We probably could do something and check for validity here, but that should definitely be configurable in the rules file as this might not apply to all languages.

So basically:

* If there is a quote, it should have two quotes
* If there are two quotes, there should be something between the two quotes

Any other case?

Side note: I'm not sure how this will impact the performance :/

**Comment by Mte90** [comment]
With the italian rules we fixed that problem https://github.com/Common-Voice/common-voice-wiki-scraper/pull/29 but apart the performance we need that fix anyway.

**Comment by jaumeortola** [comment]
These unclosed quotation marks are caused mostly by wrong sentence tokenization (see #11). This problem is very common, and we need to fix it.
