### ISSUE TITLE
Implement blacklist file

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/common-voice-wiki-scraper#33]
For the languages we have tested, we end up reducing the final list too much by removing complex or non-native words.

We need a way to filter-out a big list of words from the script, so we don't get penalized afterward.

This should be configurable in the per-language rules, and expect this list to be long.

**Comment by carlfm01** [comment]
@nukeador Here is the requested blacklist https://send.firefox.com/download/a5552b737645cd4b/#QPYHVbgReb3MHgvhYum2PQ

Unfortunately Rust is out of knowledge to help with the code to filter with the list.

Additionally, I would like to know if adding a foreign large list of stop words to the rule file is OK or should we add them to a separated file?

The stop words of language are commonly known as meaningless or common used words, in our case we want to avoid common foreign words in the Spanish sentences.

Example of the stop words:
https://github.com/carlfm01/common-voice-wiki-scraper/commit/26a98c7567f8049c509118d968cf6d9b11d28969

**Comment by Gregoor** [comment]
I've added a config option for it:
https://github.com/Common-Voice/common-voice-wiki-scraper/pull/37

Tests look good imo, not sure if anyone wants to review it (btw great work on that config code @MichaelKohler, love that test coverage 😍 )
