### ISSUE TITLE
Another approach for improving sentence selection

### ISSUE THREAD

**Issue by jaumeortola** [Common-Voice/common-voice-wiki-scraper#39]
Hi, 

I tried the script with the Catalan Wikipedia. The results are a bit disappointing. 

Some issues:
* Sentence tokenization is not good.
* There is no spelling & grammar checking. 
* Repeated sentences are not taken into account. (You can end up with 50.000 repetitions of the same sentence.) 

I wrote my own script based on LanguageTool (in Java), and I get sentences of much better quality. The script is [here](https://github.com/Softcatala/filter-wiki-corpus-lt/blob/master/src/main/java/softcatala/filterwikicorpus/filterwikicorpus.java). Are you open to use it? I am told that the extraction of sentences has to be executed by Mozilla staff.

This script could be used for other [languages](https://languagetool.org/languages). But the quality of LanguageTool is unequal: very good for some languages, not so good for others.

**Comment by nukeador** [comment]
Hello,

Is it possible that you create a separate issue for each problem? This way we can better track and learn from your experience.

We would like to improve this script since it's the one we will be using for any language who want to extract wikipedia sentences for common voice. How can we help you and other people to get involved in improving it?

Thanks for your time!

**Comment by nukeador** [comment]
BTW, sentence duplication is being tracked in https://github.com/Common-Voice/common-voice-wiki-scraper/issues/14

**Comment by jaumeortola** [comment]
I want to share my numbers extracting sentences from the Catalan Wikipedia.
* Using LanguageTool, I get [566,792 sentences properly checked](https://github.com/Softcatala/ca-text-corpus/blob/master/data/wiki.ca.txt).
* Using your script, I get 681,352 sentences. There are around 100,000 duplicates and around 200,000 sentences with spelling, grammar errors or other things we don't want (acronyms, abbreviations...). I end up with just 365,898 good sentences. 

With some work (blacklist, more conditions...) we can improve the results of the Mozilla script. In any case, the quality and the quantity of sentences will be worse than what we already have.

**Comment by nukeador** [comment]
Spelling and grammar errors seems to be very high coming from a trusted source like Wikipedia, which already has their own QA process.

When you tried this script, did you use the rules to avoid abbreviations and a generated a blacklist to avoid complex or malformed words?

**Comment by nukeador** [comment]
It would be good to have clarity on what need to still improve for this script so we can fix it and all languages will benefit from it :-D

**Comment by jaumeortola** [comment]
Wikipedia is not a "trusted" source. Wikipedia needs a lot of spelling and grammar corrections. (I have done more than [a million edits](https://ca.wikipedia.org/wiki/Especial:CentralAuth/Langtoolbot) on Wikipedia), and much more are needed. Anyway, most of the "misspellings" are just unusual proper nouns. 

Some of these problems can be mitigated, of course, with blacklists and other conditions. I'm looking into it. 

The blacklist process that you propose is very poor. The results are obviously not good. You need, at the very least, to check with some dictionary. But spell checking is not easy. Every language has some hard issues, for example regarding word tokenization.  

I can create a more or less good blacklist for my language (with the help of a dictionary). That's what I'm doing now. But it requires a lot of expertise and it can not be generalized to other languages. 

My suggestion is to use existing spelling & grammar checkers, when possible. Don't reinvent the wheel.

**Comment by MichaelKohler** [comment]
Sentence tokenization is tracked in https://github.com/Common-Voice/common-voice-wiki-scraper/issues/11
Deduplication is tracked in https://github.com/Common-Voice/common-voice-wiki-scraper/issues/14
Spelling and grammer can be done through the blacklist.

-> I'm closing this
