### ISSUE TITLE
Encoding error when trying to extract

### ISSUE THREAD

**Issue by mozillakab** [Common-Voice/common-voice-wiki-scraper#44]
When trying to extract kabyle content,  I got an encoding error. 
I replaced the content of cp1252.py (Western Europe) with the content of utf_8.py (all languages). 
It worked for me.

**Comment by MichaelKohler** [comment]
Where exactly is this happening? In the WikiExtractor itself? If so, let's close this here and report it upstream at https://github.com/attardi/wikiextractor

**Comment by mozillakab** [comment]
I will try to extract again and send the message. I got an encoding error.

**Comment by mozillakab** [comment]
## Python version on Windows7 64 bits##
C:\tal\extractwiki\wikiextractor>python --version
Python 3.6.1

##Bug reproduction##
C:\tal\extractwiki\wikiextractor>python WikiExtractor.py --json ../kabwiki-lates
t-pages-articles-multistream.xml
Traceback (most recent call last):
  File "WikiExtractor.py", line 3296, in <module>
    main()
  File "WikiExtractor.py", line 3282, in main
    args.compress, args.processes)
  File "WikiExtractor.py", line 2874, in process_dump
    for line in input:
  File "C:\Python36\lib\fileinput.py", line 250, in __next__
    line = self._readline()
  File "C:\Python36\lib\fileinput.py", line 364, in _readline
    return self._readline()
  File "C:\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 7365: cha
racter maps to <undefined>

## Workarround##
I replaced the content of C:\Python36\lib\encodings\cp1252.py (Western Europe) with the content of C:\Python36\lib\encodings\utf_8.py (all languages) and it works

**Comment by MichaelKohler** [comment]
Thanks for the info, I've filed https://github.com/attardi/wikiextractor/issues/199 for this.
