### ISSUE TITLE
error: use of unstable library feature 'repr128'

### ISSUE THREAD

**Issue by stefangrotz** [Common-Voice/common-voice-wiki-scraper#45]
Hello, 
I am using rustc 1.39.0-nightly (53df91a9b 2019-08-27) on OS X 10.14.06. When I try to extract the scentences I get a lot of errors: 

> cargo run -- extract -l esperanto -d ../wikiextractor/text/ >> wiki.eo.txt
>    Compiling punkt v1.0.5
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/trainer.rs:774:7
>     |
> 774 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 785 | / bench_trainer!(
> 786 | |   bench_trainer_short,
> 787 | |   include_str!("../test/raw/sigma-wiki.txt")
> 788 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/trainer.rs:774:7
>     |
> 774 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 790 | / bench_trainer!(
> 791 | |   bench_trainer_medium,
> 792 | |   include_str!("../test/raw/npr-article-01.txt")
> 793 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/trainer.rs:774:7
>     |
> 774 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 795 | / bench_trainer!(
> 796 | |   bench_trainer_long,
> 797 | |   include_str!("../test/raw/the-sayings-of-confucius.txt")
> 798 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/trainer.rs:774:7
>     |
> 774 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 800 | / bench_trainer!(
> 801 | |   bench_trainer_very_long,
> 802 | |   include_str!("../test/raw/pride-and-prejudice.txt")
> 803 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/tokenizer.rs:722:7
>     |
> 722 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 731 | / bench_word_tokenizer!(
> 732 | |   word_tokenizer_bench_short,
> 733 | |   include_str!("../test/raw/sigma-wiki.txt")
> 734 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/tokenizer.rs:722:7
>     |
> 722 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 736 | / bench_word_tokenizer!(
> 737 | |   word_tokenizer_bench_medium,
> 738 | |   include_str!("../test/raw/npr-article-01.txt")
> 739 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/tokenizer.rs:722:7
>     |
> 722 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 741 | / bench_word_tokenizer!(
> 742 | |   word_tokenizer_bench_long,
> 743 | |   include_str!("../test/raw/the-sayings-of-confucius.txt")
> 744 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/tokenizer.rs:722:7
>     |
> 722 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 746 | / bench_word_tokenizer!(
> 747 | |   word_tokenizer_bench_very_long,
> 748 | |   include_str!("../test/raw/pride-and-prejudice.txt")
> 749 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/tokenizer.rs:753:7
>     |
> 753 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 769 | / bench_sentence_tokenizer!(
> 770 | |   bench_sentence_tokenizer_train_on_document_short,
> 771 | |   include_str!("../test/raw/sigma-wiki.txt")
> 772 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/tokenizer.rs:753:7
>     |
> 753 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 774 | / bench_sentence_tokenizer!(
> 775 | |   bench_sentence_tokenizer_train_on_document_medium,
> 776 | |   include_str!("../test/raw/npr-article-01.txt")
> 777 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error[E0658]: use of unstable library feature 'test': `bench` is a part of custom test frameworks which are unstable
>    --> /Users/sgrotz/.cargo/registry/src/github.com-1ecc6299db9ec823/punkt-1.0.5/src/tokenizer.rs:753:7
>     |
> 753 |       #[bench] fn $name(b: &mut ::test::Bencher) {
>     |         ^^^^^
> ...
> 779 | / bench_sentence_tokenizer!(
> 780 | |   bench_sentence_tokenizer_train_on_document_long,
> 781 | |   include_str!("../test/raw/pride-and-prejudice.txt")
> 782 | | );
>     | |__- in this macro invocation
>     |
>     = note: for more information, see https://github.com/rust-lang/rust/issues/50297
>     = help: add `#![feature(test)]` to the crate attributes to enable
> 
> error: aborting due to 11 previous errors
> 
> For more information about this error, try `rustc --explain E0658`.
> error: Could not compile `punkt`.
> 
> To learn more, run the command again with --verbose.

rustc --explain E0658 tells me to install the nightly version wich I already have or to change things in the code, wich shouldn't be necessary. This must be an error on my local system. How can I fix this?

**Comment by nukeador** [comment]
Maybe something on the nightly build is broken? Can you try to install a previous version?

**Comment by stefangrotz** [comment]
Thanks. I switched my Version with 
rustup install nightly-2019-07-04
Still the same error.

**Comment by stefangrotz** [comment]
Most of the errors might be fixed with https://github.com/ferristseng/rust-punkt/issues/14
It runs with less errors on linux, but I still can't build it.

**Comment by stefangrotz** [comment]
I used multirust ( https://gist.github.com/mre/22c3ae35b2aa3fbf9a18 ) and tied random nightlies from the last months. 2019-07-04 worked.
