### ISSUE TITLE
Skip offensive language

### ISSUE THREAD

**Issue by nukeador** [Common-Voice/common-voice-wiki-scraper#6]
We should avoid getting sentences from places where we know there is offensive language.

Categories: "Profanity", "Sexual slang", "Pejorative terms for people"

**Comment by dabinat** [comment]
There should probably be a profanity filter in the script too, just for safety. I don't know if we can rely on everything being correctly tagged in the profanity category.

**Comment by nukeador** [comment]
We can probably fix this with #33
