### ISSUE TITLE
Using the language.toml rules for other big sentence collections

### ISSUE THREAD

**Issue by stefangrotz** [Common-Voice/common-voice-wiki-scraper#60]
On discourse [we are discussing](https://discourse.mozilla.org/t/using-the-europarl-dataset-with-sentences-from-speeches-from-the-european-parliament/50184) to import a big multi language sentence corpus called [Europarl](http://www.statmt.org/europarl/), containing sentences from debates in the European Parliament in 20 European languages. When I [experimented](https://github.com/stefangrotz/common-voice-work-files/tree/master/Deutsch/europarl-de-v7) with the German collection I heavily used the [german.tombl](https://github.com/Common-Voice/common-voice-wiki-scraper/blob/master/src/rules/german.toml) file as a template for rules to edit the corpus. 

This brought me to the idea that it would be great if one could use this scrapper for all kind of big sentence collections. This would establish equal rules over all kind of imports and could help people a lot who are not good with regex ;) I am talking about just applying the rules from the language.tombl file to the sentences, but no 3 sentence per page rule, etc.

Is this already possible? If not then I would like to add this functionality to the scripts. How could this be done?

**Comment by MichaelKohler** [comment]
I agree. Maybe we could have a "type" flag when running and depending on that we would use a different data source (wikipedia files or a normal text file, or whatever we need). Then all these types could eventually use the check method.

What do you think?

**Comment by MichaelKohler** [comment]
Ah, one type that might also be useful (and possibly is the same for Europarl), we could have one sentence file input, and it outputs all sentences that are valid according to the toml config files. This would for example be interesting to be fed with the wiki export files once a language has changed some rules (as we did for German). This would then filter out some sentences that were valid when the export was run, but are not deemed valid anymore.

**Comment by stefangrotz** [comment]
Simplest approach could be to format the sentence collection as one big article and then set the MAX_SENTENCES_PER_ARTICLE to a number higher than the number of imported sentences.

**Comment by MichaelKohler** [comment]
Mh, that sounds hacky and requires work every single time we want to run it. Also this wouldn't help us prepare for other possible data sources.

**Comment by stefangrotz** [comment]
True. I don't know Rust, but I will have a look into it this evening. I am sure there is a way to just use the rules for every line of a file. The test code that [tests single lines](https://github.com/Common-Voice/common-voice-wiki-scraper/blob/7443ab81bacb747783af38d497bfcdbcd55db29b/src/checker.rs#L382) looks like it could be done.

**Comment by nukeador** [comment]
Thanks for opening this. Definitely, multi-source support is something we would like to see for this tool, it would me amazing if you can coordinate a plan for it here!

**Comment by MichaelKohler** [comment]
I think I've added the base needed to support other types of sources here: https://github.com/Common-Voice/common-voice-wiki-scraper/pull/79

https://github.com/Common-Voice/common-voice-wiki-scraper/blob/master/README.md#adding-another-scrape-target
