### ISSUE TITLE
Enforce min / max sentence length

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/common-voice-wiki-scraper#7]
Some sentences are too short to be useful:

> Richard Denton.

> Jun.

> vii.

> Pomeroy et al.

> I.e.

While others are quite long and tedious:

> Pavel Melnikov-Pechersky, Velimir Khlebnikov, Pyotr Boborykin, Eugenia Ginzburg, Leo Tolstoy, Daniil Mordovtsev, Alexander Tarasov-Rodionov.

> The name was contrived by the railway for publicity and to outdo Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.

> Approaches include positivism, interpretivism, rational choice theory, behaviouralism, structuralism, post-structuralism, realism, institutionalism, and pluralism.

So it would therefore make sense to implement a minimum number of words (in my validation script I chose 3) and a maximum number of words and/or characters (I chose 14 words and 100 characters). There should also probably be a maximum word length to avoid unpronounceable scientific terms.

**Comment by nukeador** [comment]
This should be now solved by the language rules:

https://github.com/Common-Voice/common-voice-wiki-scraper/blob/master/src/rules/english.toml

**Comment by MichaelKohler** [comment]
@nukeador well, this could be solved by that, however currently the minimum words for English is still set to 1. We might want to set a better minimum in case we ever do another export.  So the question is, will we? If not, I guess we could close this issue.

**Comment by nukeador** [comment]
Agree.
