### ISSUE TITLE
Filter sentences with non-English characters

### ISSUE THREAD

**Issue by dabinat** [Common-Voice/common-voice-wiki-scraper#8]
There are multiple sentences with non-English characters such as:

> At that time Ueshiba was referring to his martial art as "Aiki Budō".

> He was from the area of Álftafjörður in west Iceland.

These characters are not supported by DeepSpeech in English and are probably unpronounceable to a lot of native English speakers.

While some English words do have accents like `café` or `naïve`, I think it's best to err on the side of caution and filter out all accents. The few words that require accents can always be submitted manually through Sentence Collector.

**Comment by nukeador** [comment]
Maybe related with #23 and #24 ?

**Comment by nukeador** [comment]
Let's track this in the individual issues listed.
